src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Publication::class, inversedBy="Commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $publication;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Source;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getPublication(): ?Publication
    {
        return $this->publication;
    }

    public function setPublication(?Publication $publication): self
    {
        $this->publication = $publication;

        return $this;
    }

    public function getSource(): ?User
    {
        return $this->Source;
    }

    public function setSource(?User $Source): self
    {
        $this->Source = $Source;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="Destination")
     */
    private $contacts;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Ville;

    /**
     * @ORM\OneToMany(targetEntity=Publication::class, mappedBy="Source")
     */
    private $publications;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="Source")
     */
    private $commentaires;

    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->publications = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(?int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setDestination($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->contains($contact)) {
            $this->contacts->removeElement($contact);
            // set the owning side to null (unless already changed)
            if ($contact->getDestination() === $this) {
                $contact->setDestination(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    /**
     * @return Collection|Publication[]
     */
    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): self
    {
        if (!$this->publications->contains($publication)) {
            $this->publications[] = $publication;
            $publication->setSource($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): self
    {
        if ($this->publications->contains($publication)) {
            $this->publications->removeElement($publication);
            // set the owning side to null (unless already changed)
            if ($publication->getSource() === $this) {
                $publication->setSource(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setSource($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getSource() === $this) {
                $commentaire->setSource(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('password', PasswordType::class)
            ->add('tel')
            ->add('nom')
            ->add('prenom')
            ->add('pays')
            ->add('ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Publication;
use App\Entity\User;
use App\Form\CommentaireType;
use App\Form\PublicationType;
use App\Form\RegistrationFormType;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/profil", name="profil")
     */
    public function index(Request $request,UserPasswordEncoderInterface $passwordEncoder)
    {
        $utilisateur=$this->get('security.token_storage')->getToken()->getUser();
       /* $repositoryUtilisateur = $this->getDoctrine()->getRepository(User::class);
        $utilisateur->$repositoryUtilisateur->find($utilisateur);*/


        $mdp = $utilisateur->getPassword();

        $form = $this->createForm(UserType::class, $utilisateur);
        $form->add('submit', SubmitType::class, ['label'=>'Modifier', 'attr'=>['class'=>'btn-primary']]);
        $form->handleRequest($request);
        $error=null;
        if ($form->isSubmitted()) {
            $motDePasse=$request->request->get('mdp');
                if (strlen($motDePasse)>=6 or $motDePasse=="")
                {
                    $entityManager = $this->getDoctrine()->getManager();

                    if ($motDePasse!=="")
                    {
                        $motDePasse = $passwordEncoder->encodePassword($utilisateur, $motDePasse);
                        $utilisateur->setPassword($motDePasse);
                    }
                    else
                    {
                        $utilisateur->setPassword($mdp);
                    }
                    $entityManager->persist($utilisateur);
                    $entityManager->flush();
                    $this->addFlash('success', 'Profil mis à jour avec succès!');
                }
                else
                {
                    $error="Mot de passe trop court. Il doit avoir au minimum 6 caractères.";
                }
        }

        return $this->render('user/index.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
            'mdp' => $mdp,
            'error' => $error
        ]);
    }


    /**
     * @Route("/mes-offres", name="mes-offres")
     */
    public function mes_offres(Request $request)
    {
        $utilisateur=$this->get('security.token_storage')->getToken()->getUser();
        $liste_publications = $utilisateur->getPublications();

        $publication = new Publication();
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {


            $form->getData();
            $publication = $form->getData();
            $publication->setSource($utilisateur);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($publication);
            $entityManager->flush();

            return $this->render('user/mes-offres.html.twig', [
                'form' => $form->createView(),
                'liste_publications' => $liste_publications,
            ]);
        }
        return $this->render('user/mes-offres.html.twig',[
            'form' => $form->createView(),
            'liste_publications' => $liste_publications,
        ]);
    }

    /**
     * @Route("/offre/{id}", name="offre", requirements={"page"="\d+"})
     */
    public function offre(int $id,Request $request)
    {
        $publication = $this->getDoctrine()
            ->getRepository(Publication::class)
            ->find($id);
        $utilisateur=$this->get('security.token_storage')->getToken()->getUser();
        $commentaires= $publication->getCommentaires();
        $commentaire = new Commentaire();


        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {

            $form->getData();
            $commentaire = $form->getData();
            $commentaire->setSource($utilisateur);
            $commentaire->setPublication($publication);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->render('user/offre.html.twig',[
                'publication' => $publication,
                'utilisateur' => $utilisateur,
                'commentaires' => $commentaires,
                'form' => $form->createView(),
            ]);
        }
        return $this->render('user/offre.html.twig',[
            'publication' => $publication,
            'utilisateur' => $utilisateur,
            'commentaires' => $commentaires,
            'form' => $form->createView(),
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <!-- Main layout -->
    <br><br><br><br><br><br>
    <main>
        <div class="row">
                    <div class="col-lg-4 mb-4">
                    <div class="card">
                    <h5 class="card-header">Mes Informations</h5>
                    <div class="card-body">
                    <h6 class="card-title">Nombre d'offres:</h6> ...

                    </div>
                    </div>

                    </div>

        <div class="col-lg-8 mb-4">
            <div class="card">
                <h5 class="card-header">Modifier le profil</h5>
                <div class="card-body">
                    <div class="card-body card-body-cascade text-center">
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ form_row(form.nom) }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ form_row(form.prenom) }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ form_row(form.tel) }}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ form_row(form.email) }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="md-form mb-0">
                                    {{ form_row(form.pays) }}
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="md-form mb-0">
                                    {{ form_row(form.ville) }}
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="md-form mb-0">

                                    <label for="mdp" data-error="az" >Mot de passe</label>
                                    <input type="password" name="mdp" id="mdp" class="form-control">

                                    {% if error!=null %}
                                        <span class="invalid-feedback d-block"><span class="d-block">
                    <span class="form-error-icon badge badge-danger text-uppercase">Erreur</span> <span class="form-error-message">{{ error }}</span>
                </span></span>{% endif %}

                                    {{ form_widget(form.password,{'attr': {'value': mdp,'hidden':true}}) }}

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 text-center my-4">
                                {{ form_row(form.submit,{'attr': {'class': 'btn-info'}}) }}
                            </div>
                        </div>
                    </div>
                    {{ form_end(form) }}
                </div>

            </div>

        </div>
        </div>
    </main>
{% endblock %}

templates/user/mes-offres.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes offres{% endblock %}

{% block body %}
    {% block Addoffre_modal %}
        <div class="modal fade Addoffre-modal mt-5" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-notify modal-warning" role="document">
                <!--Content-->
                <div class="modal-content">
                    <!--Header-->
                    <div class="modal-header text-center py-2 custum_header">
                        <h4 class="modal-title white-text w-100 font-weight-bold py-2">Ajouter Offre</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" class="white-text">&times;</span>
                        </button>
                    </div>

                    <!--Body-->
                    <div class="modal-body">
                        {{ form(form) }}
                    </div>
                </div>
                <!--/.Content-->
            </div>
        </div>

    {% endblock %}
    <br><br><br><br><br><br><br>
    <div class="card">
        <br>
        <button type="button" class="btn btn-info col-2 ml-3" data-toggle="modal" data-target=".Addoffre-modal">
            Ajouter
        </button>
        <div class="card-body">
            <table class="table">
                <thead class="">
                <tr>
                    <th scope="col">#id</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Contenu</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for publication in liste_publications|reverse %}
                <tr>
                    <th scope="row">{{ publication.id}}</th>
                    <td>{{ publication.titre}}</td>
                    <td>{{ publication.contenu}}</td>
                    <td><a class="btn btn-primary" href="{{ path('offre', { 'id': publication.id }) }}" role="button">Ouvrir</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

templates/user/offre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes offres{% endblock %}

{% block body %}

    <br><br><br><br><br><br><br>
    <div class="card">
        <div class="card-header">
            <h5>Titre :</h5>{{ publication.titre }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Description</h5>
            <p class="card-text">{{ publication.contenu }}</p>
        </div>
        <div class="card-footer text-muted">
            <h5 class="card-title pb-2">Commentaires : </h5>
            {% for commentaire in commentaires %}
            <div class="card border-primary text-center  mt-2"  >
                <div class="card-header">{{ commentaire.source.prenom }} {{ commentaire.source.nom }}</div>
                <div class="card-body text-primary">
                    <p class="card-text">{{ commentaire.contenu }}</p>
                </div>
            </div>
            {% endfor %}

            <div class="card border-primary mt-2"  >
                <div class="card-header">{{ utilisateur.prenom }} {{ utilisateur.nom }}</div>
                <div class="card-body text-primary">
                    <p class="card-text"> {{ form(form) }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}